### ISSUE TITLE
AWS marketplace - MISP not found

### ISSUE THREAD

**Issue by rebaker501** [MISP/misp-cloud#10]
The MISP template is no longer found on the AWS marketplace.  We have searched, per the instructions.

**Comment by 0xtf** [comment]
The AMI's are not in the marketplace as they are not sold. They'll be listed in the "Community AMI's", as demonstrated in the first image of the installation guide:

https://github.com/misp/misp-cloud/wiki/AWS-Installation-Guide

If that is not the case, please re-open this issue.

Thank you.

**Comment by krraghavanai** [comment]
This is not found.  I realize this is an old bug but the issue is there again

![image](https://github.com/user-attachments/assets/5bbf8d35-08da-4965-a075-8c597ec409f0)
