### ISSUE TITLE
AWS - Request aws-builds for ap-south region

### ISSUE THREAD

**Issue by himanshudas** [MISP/misp-cloud#11]
Hello @0xtf ,

Could we please expect MISP AMI in AWS ap-south(Mumbai) region?

**Comment by 0xtf** [comment]
Hi @himanshudas,

Of course! I'll add it to the template for future builds and a manual copy to Mumbai has been initiated. You'll be able to find the image _(shortly)_ in the Community AMI's or via the following identifier: **ami-07d3e6aeb6a991251**

I'll update this issue in a little after Mumbai is added to the build template.

**Comment by himanshudas** [comment]
@0xtf , This is of great help. Thank you so much!

**Comment by 0xtf** [comment]
ap-south-1 has been added to the build template and, from now on, will be part of the build process.
