### ISSUE TITLE
AWS marketplace - misp-cloud not published

### ISSUE THREAD

**Issue by adulau** [MISP/misp-cloud#12]
AWS marketplace - misp-cloud not published. is there a way to make it public?

**Comment by 0xtf** [comment]
All AMI's are public, but they are under "Community AMI's" and not the Marketplace, as that usually involves a a subscription/sale. Is that what you're referring to? 

We could "publish" in Marketplace but that entails a few logistic details that we should probably discuss first.

**Comment by adulau** [comment]
Indeed. I discovered it as we had a discussion with a cloud provider showing that you cannot install it from AWS. As long as you know the AMI, it's fine. It's just a matter of convenience when people search for MISP to find it without knowing the AMI in advance ;-)

**Comment by 0xtf** [comment]
You can install it from AWS and there is no need to know the AMI ID either
(they are only shared here for confirmation and if you want to automate
deployment).

The installation instructions show that use case, where a user just
searches for “MISP” without knowing the AMI ID:

https://github.com/misp/misp-cloud/wiki/AWS-Installation-Guide

We can publish in marketplace (for example through 3CORESec as an AWS
Technology Partner) but it would be for different reasons, as it would not
add anything to that particular use case.

**Comment by 0xtf** [comment]
Let me know if you'd like to consider publishing MISP in the Marketplace, either through a Technology Partner or as a ISV.
