### ISSUE TITLE
doc: How to upgrade?

### ISSUE THREAD

**Issue by Brueggus** [MISP/misp-cloud#16]
Thanks for the extensive information about setting up misp-cloud!

I'm wondering if there's anything worth knowing about running misp-cloud (like upgrading MISP, misp-modules, the underlying OS/software packages etc.) Would we upgrade a misp-cloud instance like any other MISP instance? Would we just deploy a new instance when there's a new version?

Could you provide some documentation in the Wiki?

**Comment by 0xtf** [comment]
Hi,

You would update a misp-cloud instance as any other MISP installation. The reason we don't provide separate documentation is because nothing differs in the cloud installation process, so you are welcome to follow the existing docs.

**Comment by Brueggus** [comment]
Thanks for clarification!
