### ISSUE TITLE
SSH Username

### ISSUE THREAD

**Issue by ghost** [MISP/misp-cloud#18]
What is the username to access SSH? I tried the default ubuntu, root, ec2-user , and even admin. I am not able to access ssh? Could you add this info to the instructions? I see the MISP username info, just not for ssh.

$ chmod 440 sshkey.pem
$ ssh -i sshkey.pem username@ip

**Comment by ghost** [comment]
The username for ssh is: ubuntu

**Comment by 0xtf** [comment]
https://github.com/MISP/misp-cloud/commit/d569bca3fffb1aa1dc9aa588b776ae454af2139e
