### ISSUE TITLE
MISP High Availability

### ISSUE THREAD

**Issue by Sreejith2k** [MISP/misp-cloud#27]
Thanks for sharing the MISP HA - https://www.youtube.com/watch?v=lUK3otmIcH4 

Would you mind sharing the IaC (CloudFormation/Terraform)? 

I am having some challenges with the RDS where no data is getting written into the RDS instead it's getting written into the EFS volume. Cross-checked the Security Group and it looks good. Also, I can manually create the tables in the RDS instances.

**Comment by 0xtf** [comment]
Hi,

Glad you found it useful. Unfortunately I do not have CF or TF configurations.

All the information for HAMISPA is in https://github.com/0xtf/HAMISPA.

**Comment by Sreejith2k** [comment]
Thanks a lot for your prompt response. 
Just a quick question, did you make any changes to the actual MISP code to make it work with RDS and EFS? When the data is pulled from the various IOC's sources, how it will get written into the RDS (I have connected my EC2 instance to the RDS using mysql -h <endpoint> -P 3306 -u <mymasteruser> -p) and its connected. 

Your response is much appreciated.
