### ISSUE TITLE
us-west-2 Does not have the images

### ISSUE THREAD

**Issue by sillyfatcat** [MISP/misp-cloud#4]
Hello everyone, us-west2 doesn't appear to have the images, would it be possible to create them? Thank you

**Comment by 0xtf** [comment]
Hi @sshum00,

Sure! Already added it to the list of regions the AMI is copied to. Will be pushed in the next build. I'll try and do that today or tomorrow.

**Comment by 0xtf** [comment]
Performed a manual copy so that you wouldn't have to wait for the build process. The file has been updated to include this new location.

us-west-2:ami-03d8cade223c03b2d

The new region will also be part of the normal build process from now on. 

Enjoy!

**Comment by sillyfatcat** [comment]
Thanks, just got it set up.

**Comment by wifiuk** [comment]
there are no UK based images ..
