### ISSUE TITLE
Event fetching not pulling events

### ISSUE THREAD

**Issue by ibinasaker** [MISP/misp-cloud#8]
I enabled all the feeds in MISP and pressed on "fetch and store all feeds"
Then I deleted all the feeds (storage shows small effect) 
Then tried to fetch it again but I only got few feeds

**Comment by 0xtf** [comment]
Can you be a bit more specific, namely what feeds failed to download? Did they work when you first fetched them?

**Comment by 0xtf** [comment]
Please re-open if applicable. Thank you.
