### ISSUE TITLE
unable to get to the diagnostics tab on the UI

### ISSUE THREAD

**Issue by alinamd** [MISP/misp-cloud#9]
I created an ec2 using the community misp ami. I can get to "Server Settings & Maintenance" with no issues to include all of the tabs EXCEPT "Diagnostics". When I try to click on Diagnostics I get: 
Error: an internal error has occurred

Is there a configuration somewhere I am missing, that I was suppose to do?

**Comment by mmorr33** [comment]
I've been having the same issue. Easily reproduced on a fresh instance using the community MISP AMI and the Diagnostics page throws an internal error whenever you try to navigate to it. Appears that there is an issue with the path to php? Any support on this? 

[Wed Apr 10 05:13:28.925451 2019] [php7:error] [pid 12966] [client 24.126.235.80:59227] PHP Fatal error:  require_once() [<a href='http://php.net/function.require'>function.require</a>]: Failed opening required 'Crypt/GPG.php' (include_path='.:/usr/share/php') in /var/www/MISP/app/Model/Server.php on line 3859, referer: https://3.84.22.230/servers/serverSettings

**Comment by mmorr33** [comment]
@alinamd Quick update - fixed by doing the following:

sudo pear install /var/www/MISP/INSTALL/dependencies/Console_CommandLine/package.xml
sudo pear install /var/www/MISP/INSTALL/dependencies/Crypt_GPG/package.xml

Hope this helps!

Regards,

Mark

**Comment by 0xtf** [comment]
@mmorr33 thank you for the feedback. I'll change the bootstrap script to include that. I'll leave this open until changes land in the images.

**Comment by 0xtf** [comment]
Could no longer reproduce this on the images that were released today. Thank you @alinamd and @mmorr33 for the help and feedback. 

Feel free to let us know of any other problems or if this one happens again.
